### ISSUE TITLE
Python3 error running script : No module named 'functionfs'

### ISSUE THREAD

**Issue by JTourteau** [ali1234/pymtpd#1]
Hi,

I just tried your mtp-responder implementation on a raspberry pi zero and I faced a problem with functionfs python module import.

I cloned the repo on the rpi and installed it as recommended 

```
$ pip3 install .
Processing /home/pi/pymtpd
Collecting construct (from mtp==0.1)
Collecting functionfs (from mtp==0.1)
Collecting inotify-simple (from mtp==0.1)
Collecting libaio (from mtp==0.1)
Collecting ioctl-opt (from functionfs->mtp==0.1)
Installing collected packages: construct, ioctl-opt, functionfs, inotify-simple, libaio, mtp
  Running setup.py install for mtp ... done
Successfully installed construct-2.8.20 functionfs-0.3 inotify-simple-1.1.7 ioctl-opt-1.2 libaio-0.2 mtp-0.1
```

However when I try to run it I have the following exception

```
$ sudo ./pymtpd --udc 20980000.usb
Traceback (most recent call last):
  File "./pymtpd", line 5, in <module>
    import mtp
  File "/home/pi/pymtpd/mtp/__init__.py", line 1, in <module>
    from mtp.function import MTPFunction
  File "/home/pi/pymtpd/mtp/function.py", line 3, in <module>
    import functionfs
ImportError: No module named 'functionfs'
```
That's strange because the module is installed and can be imported from python3 prompt

```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import functionfs
>>> functionfs.
Display all 104 possibilities? (y or n)
functionfs.ALL_CTRL_RECIP                 functionfs.INTERFACE_REVMAP               functionfs._INFINITY                      functionfs.__reduce_ex__(
functionfs.BIND                           functionfs.OSDescHeader(                  functionfs._ONCE                          functionfs.__repr__(
functionfs.CLEAR_HALT                     functionfs.OSExtCompatDesc(               functionfs.__all__                        functionfs.__setattr__(
functionfs.CONFIG0_SETUP                  functionfs.OSExtPropDescHead(             functionfs.__cached__                     functionfs.__sizeof__(
functionfs.DESCRIPTORS_MAGIC              functionfs.RESUME                         functionfs.__class__(                     functionfs.__spec__
functionfs.DESCRIPTORS_MAGIC_V2           functionfs.SETUP                          functionfs.__delattr__(                   functionfs.__str__(
functionfs.DISABLE                        functionfs.STRINGS_MAGIC                  functionfs.__dict__                       functionfs.__subclasshook__(
functionfs.DescsHead(                     functionfs.SUSPEND                        functionfs.__dir__(                       functionfs.ch9
functionfs.DescsHeadV2(                   functionfs.StringBase(                    functionfs.__doc__                        functionfs.common
functionfs.ENABLE                         functionfs.StringsHead(                   functionfs.__eq__(                        functionfs.ctypes
functionfs.ENDPOINT_DESC                  functionfs.UNBIND                         functionfs.__file__                       functionfs.errno
functionfs.ENDPOINT_REVMAP                functionfs.USBDescriptorHeader(           functionfs.__format__(                    functionfs.fcntl
functionfs.Endpoint0File(                 functionfs.USBEndpointDescriptor(         functionfs.__ge__(                        functionfs.functionfs
functionfs.EndpointFile(                  functionfs.USBEndpointDescriptorNoAudio(  functionfs.__getattribute__(              functionfs.getDescriptor(
functionfs.EndpointFileBase(              functionfs.USBInterfaceDescriptor(        functionfs.__gt__(                        functionfs.getDescs(
functionfs.EndpointINFile(                functionfs.USB_DIR_IN                     functionfs.__hash__(                      functionfs.getDescsV2(
functionfs.EndpointOUTFile(               functionfs.USB_DT_ENDPOINT                functionfs.__init__(                      functionfs.getOSDesc(
functionfs.Event(                         functionfs.USB_ENDPOINT_HALT              functionfs.__le__(                        functionfs.getOSExtPropDesc(
functionfs.FIFO_FLUSH                     functionfs.USB_RECIP_ENDPOINT             functionfs.__loader__                     functionfs.getStrings(
functionfs.FIFO_STATUS                    functionfs.USB_RECIP_INTERFACE            functionfs.__lt__(                        functionfs.io
functionfs.FLAGS(                         functionfs.USB_RECIP_MASK                 functionfs.__name__                       functionfs.itertools
functionfs.Function(                      functionfs.USB_REQ_CLEAR_FEATURE          functionfs.__ne__(                        functionfs.le32(
functionfs.HAS_FS_DESC                    functionfs.USB_REQ_GET_STATUS             functionfs.__new__(                       functionfs.os
functionfs.HAS_HS_DESC                    functionfs.USB_REQ_SET_FEATURE            functionfs.__package__                    functionfs.serialise(
functionfs.HAS_MS_OS_DESC                 functionfs.USB_TYPE_MASK                  functionfs.__path__                       functionfs.struct
functionfs.HAS_SS_DESC                    functionfs.USB_TYPE_STANDARD              functionfs.__reduce__(                    functionfs.warnings
```
Also I configured both `/etc/modules` and `/boot/config.txt` as they should be.
```
$ cat /etc/modules
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.


### PERSO : Enable USB composite driver
libcomposite
```
```
$ cat /boot/config.txt 
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

### PERSO : Enable USB device mode
dtoverlay=dcw2
```

I'll continue to investigate but I though maybe you already faced the same issue or you know a workaround to makes it work .

**Comment by JTourteau** [comment]
Apparently the error came from the fact I installed with `pip3 install .`. Using `sudo pip3 install .` instead makes functionfs module to be loaded successfully.
