### ISSUE TITLE
Error running script : FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/config/usb_gadget/g1/functions/ffs.mtp'

### ISSUE THREAD

**Issue by JTourteau** [ali1234/pymtpd#2]
Hi,

I'm trying your python script on a Raspberry Pi Zero and I face the following error running it : 

```
root@raspberrypi:/home/pi/pymtpd# ./pymtpd --udc 20980000.usb
Configuring gadget
Traceback (most recent call last):
  File "./pymtpd", line 95, in <module>
    with MTPGadget(name='g1', vid='0x0430', pid='0xa4a2') as g:
  File "./pymtpd", line 36, in __enter__
    self.add_function_to_config('ffs.mtp', 'c.1')
  File "/home/pi/pymtpd/mtp/gadget.py", line 79, in add_function_to_config
    self.gadget.functions[function] = None
  File "/home/pi/pymtpd/mtp/gadget.py", line 51, in __setitem__
    return type(self).__setattr__(self, key, value)
  File "/home/pi/pymtpd/mtp/gadget.py", line 22, in __setattr__
    os.makedirs(os.path.join(path, key))
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/config/usb_gadget/g1/functions/ffs.mtp'
```

However both libcomposite and dwc2 modules are inserted

```
root@raspberrypi:/home/pi/pymtpd# lsmod
Module                  Size  Used by
cmac                    3134  1
bnep                   11917  2
hci_uart               21190  1
btbcm                   7885  1 hci_uart
bluetooth             375121  24 hci_uart,bnep,btbcm
panel_raspberrypi_touchscreen     4161  0
vc4                   135631  3
drm_kms_helper        158708  2 vc4
drm                   351003  4 vc4,panel_raspberrypi_touchscreen,drm_kms_helper
brcmfmac              269539  0
brcmutil                9911  1 brcmfmac
snd_soc_core          176256  1 vc4
snd_compress           10144  1 snd_soc_core
snd_bcm2835            23131  0
snd_pcm_dmaengine       6002  1 snd_soc_core
snd_pcm                97825  4 vc4,snd_pcm_dmaengine,snd_bcm2835,snd_soc_core
snd_timer              22706  1 snd_pcm
syscopyarea             3161  1 drm_kms_helper
sysfillrect             3716  1 drm_kms_helper
i2c_gpio                3810  0
sysimgblt               2422  1 drm_kms_helper
snd                    68784  5 snd_compress,snd_timer,snd_bcm2835,snd_soc_core,snd_pcm
fb_sys_fops             1677  1 drm_kms_helper
i2c_algo_bit            6876  1 i2c_gpio
cfg80211              527100  1 brcmfmac
rfkill                 21373  7 bluetooth,cfg80211
i2c_bcm2835             6433  0
bcm2835_gpiomem         3791  0
uio_pdrv_genirq         3718  0
fixed                   3029  0
uio                    10166  1 uio_pdrv_genirq
ax88179_178a           16314  0
dwc2                  122113  0
libcomposite           49651  8
udc_core               40452  2 dwc2,libcomposite
ip_tables              12512  0
x_tables               20921  1 ip_tables
ipv6                  384613  22
```

Do you have an idea on how to resolve this?

**Comment by JTourteau** [comment]
Because I forgot to enable CONFIGFS in kernel after recompiling it...
